# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool: ubuntu

variables:
- name: image
  value: sonoma-90gb-orka3-arm 

- name: cpu
  value: 4

- name: memory
  value: 8

steps:
- bash: |
    orka3 vm list --image ${{variables.image}} --cpu ${{variables.cpu}} --memory ${{variables.memory}}

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
