# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

jobs:
  - job: Deploy_Orka_VM
    pool: ubuntu

    variables:
    - name: image
      value: sonoma-90gb-orka3-arm 

    - name: cpu
      value: 4

    - name: memory
      value: 8

    - name: VM_NAME
      value: None

    steps:
    - script: |
        ORKA_OUTPUT=$(orka3 vm deploy --image ${{variables.image}} --cpu ${{variables.cpu}} --memory ${{variables.memory}} --generate-name azure-devops --output json)
        VM_NAME=$(echo $ORKA_OUTPUT | jq -r '.[0].name')
        echo "##vso[task.setvariable variable=VM_NAME]$VM_NAME"

    - script: |
        echo $VM_NAME

      displayName: "Deploy Orka VM"

  - job: ios_build
    pool: orka
    dependsOn: Deploy_Orka_VM
    steps:
    - script: |
        echo hello world
        
  - job: delete_VM
    pool: ubuntu
    dependsOn: ios_build
      
    steps:
      - script: |
          orka3 vm delete $Deploy_Orka_VM.VM_NAME

