# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool: ubuntu

variables:
- name: image
  value: sonoma-90gb-orka3-arm 

- name: cpu
  value: 4

- name: memory
  value: 8

steps:
- script: |
    ORKA_OUTPUT=$(orka3 vm deploy --image ${{variables.image}} --cpu ${{variables.cpu}} --memory ${{variables.memory}} --generate-name azure-devops --output json)
    echo $(ORKA_OUTPUT)
    
    # Extract values using jq
    VM_NAME=$(echo $ORKA_OUTPUT | jq -r '.[0].name')
    echo $(VM_NAME)
    # Set pipeline variables
    echo "##vso[task.setvariable variable=VM_NAME]$VM_NAME"
    echo ${{variables.VM_NAME}}
    sleep 60

  displayName: "Deploy Orka VM"

